DIVISIONS = [
    {
        "slug": "real-estate",
        "number": "01",
        "label": "REAL ESTATE",
        "title": "Real Estate",
        "image": "real-estate.jpg",
        "description": "Residential, commercial and industrial properties defined by cost-effectiveness, innovative design and sustainability.",
    },
    {
        "slug": "transportation",
        "number": "02",
        "label": "TRANSPORTATION",
        "title": "Transportation",
        "image": "transportation.jpg",
        "description": "Logistics and heavy transport services — flatbed logistics, dumper truck operations, heavy equipment rental and tanker transport across Saudi Arabia and the GCC.",
    },
    {
        "slug": "construction",
        "number": "03",
        "label": "CONSTRUCTION",
        "title": "Construction",
        "image": "construction.jpg",
        "description": "Engineering, procurement and construction across civil infrastructure, electromechanical works and site facilities, serving oil & gas, power, healthcare and industrial sectors through Turnkey, Unit Rate and cost-plus contracts.",
    },
    {
        "slug": "manufacturing",
        "number": "04",
        "label": "MANUFACTURING",
        "title": "Manufacturing",
        "image": "manufacturing.jpg",
        "description": "High-quality products for diverse markets, built on excellence, precision and innovation.",
    },
    {
        "slug": "chemicals",
        "number": "05",
        "label": "CHEMICALS",
        "title": "Chemicals",
        "image": "chemicals.jpg",
        "description": "Distribution of specialty chemicals and ingredients for the coatings, adhesives, sealants and construction industries — resins, hardeners, pigments and additives across the MENA region.",
    },
    {
        "slug": "trading",
        "number": "06",
        "label": "TRADING",
        "title": "Trading",
        "image": "trading.jpg",
        "description": "Connecting markets and facilitating the flow of goods through a global network and market knowledge.",
    },
    {
        "slug": "fine-dining",
        "number": "07",
        "label": "FINE DINING",
        "title": "Fine Dining",
        "image": "fine-dining.jpg",
        "description": "Culinary experiences built on exceptional service, quality ingredients and memorable moments.",
    },
    {
        "slug": "ultra-luxury-goods",
        "number": "08",
        "label": "ULTRA LUXURY",
        "title": "Ultra Luxury Goods",
        "image": "ultra-luxury-goods.jpg",
        "description": "Acquisition, trading and management of gems, gold and watches — maximizing value in timeless resources.",
    },
    {
        "slug": "manpower",
        "number": "09",
        "label": "MANPOWER",
        "title": "Manpower",
        "image": "manpower.jpg",
        "description": "Reliable and professional manpower solutions for cleaning, maintenance, and construction requirements. Trained and skilled personnel support residential, commercial, industrial, and construction projects, providing dependable workforce solutions.",
    },
    {
        "slug": "catering",
        "number": "10",
        "label": "CATERING",
        "title": "Catering",
        "image": "catering.jpg",
        "description": "Professional corporate catering solutions for entities, businesses, offices, events, and corporate gatherings delivered with a focus on quality, hygiene, consistency, and reliable service.",
    },
]

BRANDS = [
    {"file": "huzaifa-construction-light.png", "name": "Huzaifa Construction"},
    {"file": "huzaifa-distributions-light.png", "name": "Huzaifa Distributions"},
    {"file": "huzaifa-manpower-light.png", "name": "Huzaifa Manpower"},
    {"file": "huzaifa-transportation-light.png", "name": "Huzaifa Transportation"},
    {"file": "huzaifa-consultants-light.png", "name": "Huzaifa Consultants"},
    {"file": "huzaifa-print-light.png", "name": "Huzaifa Print"},
    {"file": "huzaifa-plastics-light.png", "name": "Huzaifa Plastics"},
    {"file": "huzaifa-catering-light.png", "name": "Huzaifa Catering"},
    {"file": "falcon-international-light.png", "name": "Falcon International"},
]
